### ISSUE TITLE
Long default values in properties make properties tables render poorly

### ISSUE THREAD

**Issue by philwebb** [spring-io/spring-doc-resources#43] opened 2020-04-21 05:09 UTC
Originally raised in [Spring Boot](https://github.com/spring-projects/spring-boot/issues/21051), I think this might be related to the new CSS.

Old: https://docs.spring.io/spring-boot/docs/2.2.x/reference/html/appendix-application-properties.html#core-properties

New: https://docs.spring.io/spring-boot/docs/2.3.0.BUILD-SNAPSHOT/reference/html/appendix-application-properties.html#core-properties

**Comment by wilkinsona** [comment] 2020-04-21 07:49
Looking at the CSS, I think the problem is that `white-space: nowrap` is now being applied to`<code>` elements where it wasn't before:

https://github.com/spring-io/spring-doc-resources/blob/7f4f4020ad947e09f38418c99781760fc145136f/src/main/sass/spring/_asciidoctor.scss#L480

Temporarily disabling that rule in the web inspector returns the layout to its previous form (but may break other things, I didn't check elsewhere).

**Comment by bclozel** [comment] 2020-04-21 09:13
Fixed with 29e3762c76f7b91487015bd5

**Closed as completed by bclozel** 2020-04-21 09:13 UTC
