### ISSUE TITLE
Horizontal scrollbar always visible

### ISSUE THREAD

**Issue by philwebb** [spring-io/spring-doc-resources#41] opened 2020-04-13 22:01 UTC
The latest Spring Boot docs always have a horizontal scrollbar visible. You can also move the docs and it overlaps the ToC. The old stylesheet doesn't seem to have the problem.

**Comment by philwebb** [comment] 2020-04-13 22:01
![Screen Shot 2020-04-13 at 3 01 17 PM](https://user-images.githubusercontent.com/519772/79165300-a6c9d400-7d97-11ea-9eed-e4f861b27f06.png)

**Comment by bclozel** [comment] 2020-04-13 22:09
This might be a duplicate of #34 - we’ll need to upgrade Spring Boot to 0.2.1 and see if it’s still there.

**Comment by Buzzardo** [comment] 2020-04-13 22:14
I have assigned it to myself to investigate. I'll start with the suggestion @bclozel made. I plan to roll through all the projects to bump to 0.2.1 anyway, and maybe that's all we need to do.

**Comment by Buzzardo** [comment] 2020-04-14 14:18
I checked Chrome, Firefox, Opera, and Safari. I got the problem on Firefox, until I refreshed Firefox. Then everything was normal again.

What version of which browser are you using, @philwebb ?

**Comment by bclozel** [comment] 2020-04-15 07:53
I think we're good with 0.2.1.RELEASE on that issue. Closing this now.

**Closed as completed by bclozel** 2020-04-15 07:53 UTC
Labels: duplicate

**Comment by philwebb** [comment] 2020-04-15 18:17
Thanks, it must have been the older version that we were using. I tried Firefox and Chrome.
